### ISSUE TITLE
Vector of pointers

### ISSUE THREAD

**Issue by IanaKhitsko** [AndreyKrysiuk/TPPS_labs#11]
https://github.com/AndreyKrysiuk/TPPS_labs/blob/c41d185c0657cccc775566bbb19cabe71171485d/EuroDiffusion/Country.h#L9

why not just std::vector<City> ?

**Comment by AndreyKrysiuk** [comment]
I am working with objects in City*** europe. Using vector<City> making just a copy of city from map, so methods of this copy doesn't change the map.
