### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by IanaKhitsko** [AndreyKrysiuk/TPPS_labs#12]
https://github.com/AndreyKrysiuk/TPPS_labs/blob/c41d185c0657cccc775566bbb19cabe71171485d/EuroDiffusion/Country.cpp#L64

std::vector<City*> is never cleaned up in destructor, you should delete each member or use smart pointers

**Comment by AndreyKrysiuk** [comment]
Actually, there is no need to clean this memory in destructor. This vector contains pointers to cities in map, and I clean map's memory in the end of each test case with function deleteMemory defined in EuroDiffusionLogic.cpp.
