### ISSUE TITLE
Prototype - Implementation convention

### ISSUE THREAD

**Issue by ChristoMI** [AndreyKrysiuk/TPPS_labs#2]
[https://github.com/AndreyKrysiuk/TPPS_labs/blob/master/EuroDiffusion/EuroDiffusion.cpp#L7](url)
[https://github.com/AndreyKrysiuk/TPPS_labs/blob/master/EuroDiffusion/EuroDiffusion.cpp#L19](url)
[https://github.com/AndreyKrysiuk/TPPS_labs/blob/master/EuroDiffusion/EuroDiffusion.cpp#L40](url)

As far as I remember, according to solid principles, a function, if used separately from class, should be declared as following:
<function_prototype_signature>
....
<code>
....
<function_prototype_implementation>

**Comment by AndreyKrysiuk** [comment]
Done
