### ISSUE TITLE
No need to write parenthesis with single line of code

### ISSUE THREAD

**Issue by ChristoMI** [AndreyKrysiuk/TPPS_labs#3]
[https://github.com/AndreyKrysiuk/TPPS_labs/blob/master/EuroDiffusion/EuroDiffusion.cpp#L56-L54](url)

**Comment by AndreyKrysiuk** [comment]
I am disagreed. In my opinion, it's more readable code. Also, when we want to extend this code, there is no need to find where we should put parenthesis.

**Comment by ChristoMI** [comment]
Ok. Closed
