### ISSUE TITLE
Out of range

### ISSUE THREAD

**Issue by IanaKhitsko** [AndreyKrysiuk/TPPS_labs#9]
https://github.com/AndreyKrysiuk/TPPS_labs/blob/c41d185c0657cccc775566bbb19cabe71171485d/EuroDiffusion/City.cpp#L57

What if europe[_x + 1][_y] is not nullptr, but has some garbage? what if _x+1 is out of range? the same for _y

**Comment by AndreyKrysiuk** [comment]
Done
